apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicelivro-deployment
  labels:
    app: servicelivro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: servicelivro
  template:
    metadata:
      labels:
        app: servicelivro
    spec:
      containers:
        - name: servicelivro
          image: servicelivro-image
          ports:
            - containerPort: 8080